// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Variable_VarType int32

const (
	Variable_GLOBAL    Variable_VarType = 0 // 全局变量
	Variable_LOCAL     Variable_VarType = 1 // 局部变量
	Variable_PARAMETER Variable_VarType = 2 // 参数
)

// Enum value maps for Variable_VarType.
var (
	Variable_VarType_name = map[int32]string{
		0: "GLOBAL",
		1: "LOCAL",
		2: "PARAMETER",
	}
	Variable_VarType_value = map[string]int32{
		"GLOBAL":    0,
		"LOCAL":     1,
		"PARAMETER": 2,
	}
)

func (x Variable_VarType) Enum() *Variable_VarType {
	p := new(Variable_VarType)
	*p = x
	return p
}

func (x Variable_VarType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Variable_VarType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_proto_enumTypes[0].Descriptor()
}

func (Variable_VarType) Type() protoreflect.EnumType {
	return &file_data_proto_enumTypes[0]
}

func (x Variable_VarType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Variable_VarType.Descriptor instead.
func (Variable_VarType) EnumDescriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6, 0}
}

type DeclRef_RefType int32

const (
	DeclRef_FUNCTION  DeclRef_RefType = 0 // 函数引用
	DeclRef_VARIABLE  DeclRef_RefType = 1 // 变量引用
	DeclRef_PARAMETER DeclRef_RefType = 2 // 参数引用
)

// Enum value maps for DeclRef_RefType.
var (
	DeclRef_RefType_name = map[int32]string{
		0: "FUNCTION",
		1: "VARIABLE",
		2: "PARAMETER",
	}
	DeclRef_RefType_value = map[string]int32{
		"FUNCTION":  0,
		"VARIABLE":  1,
		"PARAMETER": 2,
	}
)

func (x DeclRef_RefType) Enum() *DeclRef_RefType {
	p := new(DeclRef_RefType)
	*p = x
	return p
}

func (x DeclRef_RefType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeclRef_RefType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_proto_enumTypes[1].Descriptor()
}

func (DeclRef_RefType) Type() protoreflect.EnumType {
	return &file_data_proto_enumTypes[1]
}

func (x DeclRef_RefType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeclRef_RefType.Descriptor instead.
func (DeclRef_RefType) EnumDescriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7, 0}
}

type StringTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []string               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // 字符串表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTable) Reset() {
	*x = StringTable{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTable) ProtoMessage() {}

func (x *StringTable) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTable.ProtoReflect.Descriptor instead.
func (*StringTable) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *StringTable) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StringIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 字符串表索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringIndex) Reset() {
	*x = StringIndex{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringIndex) ProtoMessage() {}

func (x *StringIndex) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringIndex.ProtoReflect.Descriptor instead.
func (*StringIndex) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *StringIndex) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      *StringIndex           `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 引用字符串表中的文件名
	Line          uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        uint32                 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	Length        uint32                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetFileName() *StringIndex {
	if x != nil {
		return x.FileName
	}
	return nil
}

func (x *Location) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Location) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Location) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      *StringIndex           `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 引用字符串表中的文件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfo) GetFileName() *StringIndex {
	if x != nil {
		return x.FileName
	}
	return nil
}

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // 引用字符串表中的函数名
	ReturnType    string                 `protobuf:"bytes,2,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"` // 引用字符串表中的返回类型
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Parameters    []uint32               `protobuf:"varint,4,rep,packed,name=parameters,proto3" json:"parameters,omitempty"`
	LocalVars     []uint32               `protobuf:"varint,5,rep,packed,name=local_vars,json=localVars,proto3" json:"local_vars,omitempty"`
	IsDefinition  bool                   `protobuf:"varint,6,opt,name=is_definition,json=isDefinition,proto3" json:"is_definition,omitempty"` // 是否是函数定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

func (x *Function) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Function) GetParameters() []uint32 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Function) GetLocalVars() []uint32 {
	if x != nil {
		return x.LocalVars
	}
	return nil
}

func (x *Function) GetIsDefinition() bool {
	if x != nil {
		return x.IsDefinition
	}
	return false
}

type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncDeclIndex uint32                 `protobuf:"varint,1,opt,name=func_decl_index,json=funcDeclIndex,proto3" json:"func_decl_index,omitempty"` // 引用函数声明的索引
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                           // 引用字符串表中的函数名
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionCall) GetFuncDeclIndex() uint32 {
	if x != nil {
		return x.FuncDeclIndex
	}
	return 0
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 引用字符串表中的变量名
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 引用字符串表中的类型
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	VarType       Variable_VarType       `protobuf:"varint,4,opt,name=var_type,json=varType,proto3,enum=TopsAstProto.Variable_VarType" json:"var_type,omitempty"` // 变量类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Variable) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Variable) GetVarType() Variable_VarType {
	if x != nil {
		return x.VarType
	}
	return Variable_GLOBAL
}

type DeclRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReferencedName string                 `protobuf:"bytes,1,opt,name=referenced_name,json=referencedName,proto3" json:"referenced_name,omitempty"`
	RefType        DeclRef_RefType        `protobuf:"varint,2,opt,name=ref_type,json=refType,proto3,enum=TopsAstProto.DeclRef_RefType" json:"ref_type,omitempty"` // 引用类型
	// Types that are valid to be assigned to RefObj:
	//
	//	*DeclRef_Function
	//	*DeclRef_Variable
	RefObj        isDeclRef_RefObj `protobuf_oneof:"ref_obj"`
	Location      *Location        `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclRef) Reset() {
	*x = DeclRef{}
	mi := &file_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclRef) ProtoMessage() {}

func (x *DeclRef) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclRef.ProtoReflect.Descriptor instead.
func (*DeclRef) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7}
}

func (x *DeclRef) GetReferencedName() string {
	if x != nil {
		return x.ReferencedName
	}
	return ""
}

func (x *DeclRef) GetRefType() DeclRef_RefType {
	if x != nil {
		return x.RefType
	}
	return DeclRef_FUNCTION
}

func (x *DeclRef) GetRefObj() isDeclRef_RefObj {
	if x != nil {
		return x.RefObj
	}
	return nil
}

func (x *DeclRef) GetFunction() uint32 {
	if x != nil {
		if x, ok := x.RefObj.(*DeclRef_Function); ok {
			return x.Function
		}
	}
	return 0
}

func (x *DeclRef) GetVariable() uint32 {
	if x != nil {
		if x, ok := x.RefObj.(*DeclRef_Variable); ok {
			return x.Variable
		}
	}
	return 0
}

func (x *DeclRef) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type isDeclRef_RefObj interface {
	isDeclRef_RefObj()
}

type DeclRef_Function struct {
	Function uint32 `protobuf:"varint,3,opt,name=function,proto3,oneof"`
}

type DeclRef_Variable struct {
	Variable uint32 `protobuf:"varint,4,opt,name=variable,proto3,oneof"`
}

func (*DeclRef_Function) isDeclRef_RefObj() {}

func (*DeclRef_Variable) isDeclRef_RefObj() {}

type TranslationUnit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StringTable     []string               `protobuf:"bytes,1,rep,name=string_table,json=stringTable,proto3" json:"string_table,omitempty"` // 字符串表
	FilePath        string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`          // 引用字符串表中的文件路径
	CompileArgs     string                 `protobuf:"bytes,3,opt,name=compile_args,json=compileArgs,proto3" json:"compile_args,omitempty"`
	IncludedHeaders []*FileInfo            `protobuf:"bytes,4,rep,name=included_headers,json=includedHeaders,proto3" json:"included_headers,omitempty"`
	// repeated Function func_decls = 5;
	// repeated Function func_defs = 6;
	GlobalVars    []uint32    `protobuf:"varint,7,rep,packed,name=global_vars,json=globalVars,proto3" json:"global_vars,omitempty"`
	DeclRefs      []*DeclRef  `protobuf:"bytes,8,rep,name=decl_refs,json=declRefs,proto3" json:"decl_refs,omitempty"`
	VariableTable []*Variable `protobuf:"bytes,10,rep,name=variable_table,json=variableTable,proto3" json:"variable_table,omitempty"` // 变量表
	FunctionTable []*Function `protobuf:"bytes,11,rep,name=function_table,json=functionTable,proto3" json:"function_table,omitempty"` // 函数表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationUnit) Reset() {
	*x = TranslationUnit{}
	mi := &file_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationUnit) ProtoMessage() {}

func (x *TranslationUnit) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationUnit.ProtoReflect.Descriptor instead.
func (*TranslationUnit) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{8}
}

func (x *TranslationUnit) GetStringTable() []string {
	if x != nil {
		return x.StringTable
	}
	return nil
}

func (x *TranslationUnit) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *TranslationUnit) GetCompileArgs() string {
	if x != nil {
		return x.CompileArgs
	}
	return ""
}

func (x *TranslationUnit) GetIncludedHeaders() []*FileInfo {
	if x != nil {
		return x.IncludedHeaders
	}
	return nil
}

func (x *TranslationUnit) GetGlobalVars() []uint32 {
	if x != nil {
		return x.GlobalVars
	}
	return nil
}

func (x *TranslationUnit) GetDeclRefs() []*DeclRef {
	if x != nil {
		return x.DeclRefs
	}
	return nil
}

func (x *TranslationUnit) GetVariableTable() []*Variable {
	if x != nil {
		return x.VariableTable
	}
	return nil
}

func (x *TranslationUnit) GetFunctionTable() []*Function {
	if x != nil {
		return x.FunctionTable
	}
	return nil
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\x12\fTopsAstProto\"'\n" +
	"\vStringTable\x12\x18\n" +
	"\aentries\x18\x01 \x03(\tR\aentries\"#\n" +
	"\vStringIndex\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\"\x86\x01\n" +
	"\bLocation\x126\n" +
	"\tfile_name\x18\x01 \x01(\v2\x19.TopsAstProto.StringIndexR\bfileName\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\rR\x06column\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\"B\n" +
	"\bFileInfo\x126\n" +
	"\tfile_name\x18\x01 \x01(\v2\x19.TopsAstProto.StringIndexR\bfileName\"\xd7\x01\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vreturn_type\x18\x02 \x01(\tR\n" +
	"returnType\x122\n" +
	"\blocation\x18\x03 \x01(\v2\x16.TopsAstProto.LocationR\blocation\x12\x1e\n" +
	"\n" +
	"parameters\x18\x04 \x03(\rR\n" +
	"parameters\x12\x1d\n" +
	"\n" +
	"local_vars\x18\x05 \x03(\rR\tlocalVars\x12#\n" +
	"\ris_definition\x18\x06 \x01(\bR\fisDefinition\"~\n" +
	"\fFunctionCall\x12&\n" +
	"\x0ffunc_decl_index\x18\x01 \x01(\rR\rfuncDeclIndex\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\blocation\x18\x03 \x01(\v2\x16.TopsAstProto.LocationR\blocation\"\xd2\x01\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x122\n" +
	"\blocation\x18\x03 \x01(\v2\x16.TopsAstProto.LocationR\blocation\x129\n" +
	"\bvar_type\x18\x04 \x01(\x0e2\x1e.TopsAstProto.Variable.VarTypeR\avarType\"/\n" +
	"\aVarType\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x00\x12\t\n" +
	"\x05LOCAL\x10\x01\x12\r\n" +
	"\tPARAMETER\x10\x02\"\x9d\x02\n" +
	"\aDeclRef\x12'\n" +
	"\x0freferenced_name\x18\x01 \x01(\tR\x0ereferencedName\x128\n" +
	"\bref_type\x18\x02 \x01(\x0e2\x1d.TopsAstProto.DeclRef.RefTypeR\arefType\x12\x1c\n" +
	"\bfunction\x18\x03 \x01(\rH\x00R\bfunction\x12\x1c\n" +
	"\bvariable\x18\x04 \x01(\rH\x00R\bvariable\x122\n" +
	"\blocation\x18\x05 \x01(\v2\x16.TopsAstProto.LocationR\blocation\"4\n" +
	"\aRefType\x12\f\n" +
	"\bFUNCTION\x10\x00\x12\f\n" +
	"\bVARIABLE\x10\x01\x12\r\n" +
	"\tPARAMETER\x10\x02B\t\n" +
	"\aref_obj\"\x8a\x03\n" +
	"\x0fTranslationUnit\x12!\n" +
	"\fstring_table\x18\x01 \x03(\tR\vstringTable\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12!\n" +
	"\fcompile_args\x18\x03 \x01(\tR\vcompileArgs\x12A\n" +
	"\x10included_headers\x18\x04 \x03(\v2\x16.TopsAstProto.FileInfoR\x0fincludedHeaders\x12\x1f\n" +
	"\vglobal_vars\x18\a \x03(\rR\n" +
	"globalVars\x122\n" +
	"\tdecl_refs\x18\b \x03(\v2\x15.TopsAstProto.DeclRefR\bdeclRefs\x12=\n" +
	"\x0evariable_table\x18\n" +
	" \x03(\v2\x16.TopsAstProto.VariableR\rvariableTable\x12=\n" +
	"\x0efunction_table\x18\v \x03(\v2\x16.TopsAstProto.FunctionR\rfunctionTableB\tZ\a./;datab\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_proto_goTypes = []any{
	(Variable_VarType)(0),   // 0: TopsAstProto.Variable.VarType
	(DeclRef_RefType)(0),    // 1: TopsAstProto.DeclRef.RefType
	(*StringTable)(nil),     // 2: TopsAstProto.StringTable
	(*StringIndex)(nil),     // 3: TopsAstProto.StringIndex
	(*Location)(nil),        // 4: TopsAstProto.Location
	(*FileInfo)(nil),        // 5: TopsAstProto.FileInfo
	(*Function)(nil),        // 6: TopsAstProto.Function
	(*FunctionCall)(nil),    // 7: TopsAstProto.FunctionCall
	(*Variable)(nil),        // 8: TopsAstProto.Variable
	(*DeclRef)(nil),         // 9: TopsAstProto.DeclRef
	(*TranslationUnit)(nil), // 10: TopsAstProto.TranslationUnit
}
var file_data_proto_depIdxs = []int32{
	3,  // 0: TopsAstProto.Location.file_name:type_name -> TopsAstProto.StringIndex
	3,  // 1: TopsAstProto.FileInfo.file_name:type_name -> TopsAstProto.StringIndex
	4,  // 2: TopsAstProto.Function.location:type_name -> TopsAstProto.Location
	4,  // 3: TopsAstProto.FunctionCall.location:type_name -> TopsAstProto.Location
	4,  // 4: TopsAstProto.Variable.location:type_name -> TopsAstProto.Location
	0,  // 5: TopsAstProto.Variable.var_type:type_name -> TopsAstProto.Variable.VarType
	1,  // 6: TopsAstProto.DeclRef.ref_type:type_name -> TopsAstProto.DeclRef.RefType
	4,  // 7: TopsAstProto.DeclRef.location:type_name -> TopsAstProto.Location
	5,  // 8: TopsAstProto.TranslationUnit.included_headers:type_name -> TopsAstProto.FileInfo
	9,  // 9: TopsAstProto.TranslationUnit.decl_refs:type_name -> TopsAstProto.DeclRef
	8,  // 10: TopsAstProto.TranslationUnit.variable_table:type_name -> TopsAstProto.Variable
	6,  // 11: TopsAstProto.TranslationUnit.function_table:type_name -> TopsAstProto.Function
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	file_data_proto_msgTypes[7].OneofWrappers = []any{
		(*DeclRef_Function)(nil),
		(*DeclRef_Variable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		EnumInfos:         file_data_proto_enumTypes,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
