// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []string               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // 字符串表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTable) Reset() {
	*x = StringTable{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTable) ProtoMessage() {}

func (x *StringTable) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTable.ProtoReflect.Descriptor instead.
func (*StringTable) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *StringTable) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StringIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 字符串表索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringIndex) Reset() {
	*x = StringIndex{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringIndex) ProtoMessage() {}

func (x *StringIndex) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringIndex.ProtoReflect.Descriptor instead.
func (*StringIndex) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *StringIndex) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      *StringIndex           `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 引用字符串表中的文件名
	Line          uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        uint32                 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	Length        uint32                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetFileName() *StringIndex {
	if x != nil {
		return x.FileName
	}
	return nil
}

func (x *Location) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Location) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Location) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      *StringIndex           `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 引用字符串表中的文件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfo) GetFileName() *StringIndex {
	if x != nil {
		return x.FileName
	}
	return nil
}

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // 引用字符串表中的函数名
	ReturnType    string                 `protobuf:"bytes,2,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"` // 引用字符串表中的返回类型
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Parameters    []*Variable            `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	LocalVars     []*Variable            `protobuf:"bytes,5,rep,name=local_vars,json=localVars,proto3" json:"local_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

func (x *Function) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Function) GetParameters() []*Variable {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Function) GetLocalVars() []*Variable {
	if x != nil {
		return x.LocalVars
	}
	return nil
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 引用字符串表中的变量名
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 引用字符串表中的类型
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Variable) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type DeclRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReferencedName string                 `protobuf:"bytes,1,opt,name=referenced_name,json=referencedName,proto3" json:"referenced_name,omitempty"` // 引用字符串表中的引用名
	ReferencedType string                 `protobuf:"bytes,2,opt,name=referenced_type,json=referencedType,proto3" json:"referenced_type,omitempty"` // 引用字符串表中的引用类型
	Location       *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeclRef) Reset() {
	*x = DeclRef{}
	mi := &file_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclRef) ProtoMessage() {}

func (x *DeclRef) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclRef.ProtoReflect.Descriptor instead.
func (*DeclRef) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6}
}

func (x *DeclRef) GetReferencedName() string {
	if x != nil {
		return x.ReferencedName
	}
	return ""
}

func (x *DeclRef) GetReferencedType() string {
	if x != nil {
		return x.ReferencedType
	}
	return ""
}

func (x *DeclRef) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type TranslationUnit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StringTable     *StringTable           `protobuf:"bytes,1,opt,name=string_table,json=stringTable,proto3" json:"string_table,omitempty"` // 字符串表
	FilePath        string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`          // 引用字符串表中的文件路径
	CompileArgs     string                 `protobuf:"bytes,3,opt,name=compile_args,json=compileArgs,proto3" json:"compile_args,omitempty"`
	IncludedHeaders []*FileInfo            `protobuf:"bytes,4,rep,name=included_headers,json=includedHeaders,proto3" json:"included_headers,omitempty"`
	FuncDecls       []*Function            `protobuf:"bytes,5,rep,name=func_decls,json=funcDecls,proto3" json:"func_decls,omitempty"`
	FuncDefs        []*Function            `protobuf:"bytes,6,rep,name=func_defs,json=funcDefs,proto3" json:"func_defs,omitempty"`
	GlobalVars      []*Variable            `protobuf:"bytes,7,rep,name=global_vars,json=globalVars,proto3" json:"global_vars,omitempty"`
	DeclRefs        []*DeclRef             `protobuf:"bytes,8,rep,name=decl_refs,json=declRefs,proto3" json:"decl_refs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranslationUnit) Reset() {
	*x = TranslationUnit{}
	mi := &file_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationUnit) ProtoMessage() {}

func (x *TranslationUnit) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationUnit.ProtoReflect.Descriptor instead.
func (*TranslationUnit) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7}
}

func (x *TranslationUnit) GetStringTable() *StringTable {
	if x != nil {
		return x.StringTable
	}
	return nil
}

func (x *TranslationUnit) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *TranslationUnit) GetCompileArgs() string {
	if x != nil {
		return x.CompileArgs
	}
	return ""
}

func (x *TranslationUnit) GetIncludedHeaders() []*FileInfo {
	if x != nil {
		return x.IncludedHeaders
	}
	return nil
}

func (x *TranslationUnit) GetFuncDecls() []*Function {
	if x != nil {
		return x.FuncDecls
	}
	return nil
}

func (x *TranslationUnit) GetFuncDefs() []*Function {
	if x != nil {
		return x.FuncDefs
	}
	return nil
}

func (x *TranslationUnit) GetGlobalVars() []*Variable {
	if x != nil {
		return x.GlobalVars
	}
	return nil
}

func (x *TranslationUnit) GetDeclRefs() []*DeclRef {
	if x != nil {
		return x.DeclRefs
	}
	return nil
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\x12\fTopsAstProto\"'\n" +
	"\vStringTable\x12\x18\n" +
	"\aentries\x18\x01 \x03(\tR\aentries\"#\n" +
	"\vStringIndex\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\"\x86\x01\n" +
	"\bLocation\x126\n" +
	"\tfile_name\x18\x01 \x01(\v2\x19.TopsAstProto.StringIndexR\bfileName\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\rR\x06column\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\"B\n" +
	"\bFileInfo\x126\n" +
	"\tfile_name\x18\x01 \x01(\v2\x19.TopsAstProto.StringIndexR\bfileName\"\xe2\x01\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vreturn_type\x18\x02 \x01(\tR\n" +
	"returnType\x122\n" +
	"\blocation\x18\x03 \x01(\v2\x16.TopsAstProto.LocationR\blocation\x126\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\x16.TopsAstProto.VariableR\n" +
	"parameters\x125\n" +
	"\n" +
	"local_vars\x18\x05 \x03(\v2\x16.TopsAstProto.VariableR\tlocalVars\"f\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x122\n" +
	"\blocation\x18\x03 \x01(\v2\x16.TopsAstProto.LocationR\blocation\"\x8f\x01\n" +
	"\aDeclRef\x12'\n" +
	"\x0freferenced_name\x18\x01 \x01(\tR\x0ereferencedName\x12'\n" +
	"\x0freferenced_type\x18\x02 \x01(\tR\x0ereferencedType\x122\n" +
	"\blocation\x18\x03 \x01(\v2\x16.TopsAstProto.LocationR\blocation\"\xab\x03\n" +
	"\x0fTranslationUnit\x12<\n" +
	"\fstring_table\x18\x01 \x01(\v2\x19.TopsAstProto.StringTableR\vstringTable\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12!\n" +
	"\fcompile_args\x18\x03 \x01(\tR\vcompileArgs\x12A\n" +
	"\x10included_headers\x18\x04 \x03(\v2\x16.TopsAstProto.FileInfoR\x0fincludedHeaders\x125\n" +
	"\n" +
	"func_decls\x18\x05 \x03(\v2\x16.TopsAstProto.FunctionR\tfuncDecls\x123\n" +
	"\tfunc_defs\x18\x06 \x03(\v2\x16.TopsAstProto.FunctionR\bfuncDefs\x127\n" +
	"\vglobal_vars\x18\a \x03(\v2\x16.TopsAstProto.VariableR\n" +
	"globalVars\x122\n" +
	"\tdecl_refs\x18\b \x03(\v2\x15.TopsAstProto.DeclRefR\bdeclRefsB\tZ\a./;datab\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_data_proto_goTypes = []any{
	(*StringTable)(nil),     // 0: TopsAstProto.StringTable
	(*StringIndex)(nil),     // 1: TopsAstProto.StringIndex
	(*Location)(nil),        // 2: TopsAstProto.Location
	(*FileInfo)(nil),        // 3: TopsAstProto.FileInfo
	(*Function)(nil),        // 4: TopsAstProto.Function
	(*Variable)(nil),        // 5: TopsAstProto.Variable
	(*DeclRef)(nil),         // 6: TopsAstProto.DeclRef
	(*TranslationUnit)(nil), // 7: TopsAstProto.TranslationUnit
}
var file_data_proto_depIdxs = []int32{
	1,  // 0: TopsAstProto.Location.file_name:type_name -> TopsAstProto.StringIndex
	1,  // 1: TopsAstProto.FileInfo.file_name:type_name -> TopsAstProto.StringIndex
	2,  // 2: TopsAstProto.Function.location:type_name -> TopsAstProto.Location
	5,  // 3: TopsAstProto.Function.parameters:type_name -> TopsAstProto.Variable
	5,  // 4: TopsAstProto.Function.local_vars:type_name -> TopsAstProto.Variable
	2,  // 5: TopsAstProto.Variable.location:type_name -> TopsAstProto.Location
	2,  // 6: TopsAstProto.DeclRef.location:type_name -> TopsAstProto.Location
	0,  // 7: TopsAstProto.TranslationUnit.string_table:type_name -> TopsAstProto.StringTable
	3,  // 8: TopsAstProto.TranslationUnit.included_headers:type_name -> TopsAstProto.FileInfo
	4,  // 9: TopsAstProto.TranslationUnit.func_decls:type_name -> TopsAstProto.Function
	4,  // 10: TopsAstProto.TranslationUnit.func_defs:type_name -> TopsAstProto.Function
	5,  // 11: TopsAstProto.TranslationUnit.global_vars:type_name -> TopsAstProto.Variable
	6,  // 12: TopsAstProto.TranslationUnit.decl_refs:type_name -> TopsAstProto.DeclRef
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
